# Stage 1: Lắp ráp (Builder)
FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build 

# Stage 2: Tủ kính trưng bày (Production)
FROM nginx:alpine
# Dọn rác mặc định của nginx
RUN rm -rf /usr/share/nginx/html/*
# Lấy con mô hình đã ráp xong ở stage 1 qua
COPY --from=builder /app/dist /usr/share/nginx/html 
# Ném cái file cấu hình chống 404 vào
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]