server {
    listen 80;
    
    # Ép Nginx dùng UTF-8 để không lỗi font chữ
    charset utf-8;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # Cái này là bùa hộ mệnh của React Router:
        try_files $uri $uri/ /index.html;
    }

    # Tối ưu hóa: Cache các file tĩnh (ảnh, css, js) trên trình duyệt client
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
        root /usr/share/nginx/html;
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
    }
}