events {}

http {
    server {
        # Lắng nghe kết nối HTTPS có mã hóa
        listen 8443 ssl;
        server_name localhost;

        # 1. Khóa và Chứng chỉ của chính Nginx
        ssl_certificate /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.key;

        # 2. CẤU HÌNH mTLS (BẮT BUỘC TRÌNH THẺ NGÀNH)
        ssl_client_certificate /etc/nginx/certs/ca.crt; # Nginx dùng CA này để soi thẻ
        ssl_verify_client on; # Bật Mode: "Không thẻ ngành = CÚT"

        # 3. Chuyển tiếp Request đã hợp lệ vào Két sắt SoftHSM
        location / {
            proxy_pass http://softhsm-api:8888;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # (Tùy chọn) Gửi thông tin chứng chỉ của Client vào cho Python biết (nếu cần log)
            proxy_set_header X-Client-Verify $ssl_client_verify;
            proxy_set_header X-Client-DN $ssl_client_s_dn;
        }
    }
}