---
# BACKEND (ORDER SERVICE)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchant-backend
  namespace: merchant-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merchant-backend
  template:
    metadata:
      labels:
        app: merchant-backend
    spec:
      containers:
      - name: backend
        image: merchant-backend:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        # GIÁP mTLS CHO BACKEND MERCHANT
        volumeMounts:
        - name: cert-volume
          mountPath: /etc/certs
          readOnly: true
          
      # KHAI BÁO KHO CHỨA SECRET
      volumes:
      - name: cert-volume
        secret:
          secretName: client-certs

---
apiVersion: v1
kind: Service
metadata:
  name: merchant-backend-svc
  namespace: merchant-site
spec:
  type: ClusterIP
  selector:
    app: merchant-backend
  ports:
  - port: 80
    targetPort: 5000

---
# FRONTEND (REACTJS + NGINX)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchant-frontend
  namespace: merchant-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merchant-frontend
  template:
    metadata:
      labels:
        app: merchant-frontend
    spec:
      containers:
      - name: frontend
        image: merchant-frontend:local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: merchant-frontend-svc
  namespace: merchant-site
spec:
  type: ClusterIP
  selector:
    app: merchant-frontend
  ports:
  - port: 80
    targetPort: 80