apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-orchestrator
  namespace: nt219-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-orchestrator
  template:
    metadata:
      labels:
        app: payment-orchestrator
    spec:
      containers:
      - name: payment-orchestrator
        image: payment_orchestrator:v1
        ports:
        - containerPort: 8000
        # ĐỔI THÀNH MOUNT PATH CHUẨN
        volumeMounts:
        - name: cert-volume
          mountPath: "/certs"
          readOnly: true
        envFrom:
        - secretRef:
            name: payment-env-secret
      volumes:
      - name: cert-volume
        secret:
          secretName: master-mtls-certs
---
apiVersion: v1
kind: Service
metadata:
  name: payment-orchestrator-service
  namespace: nt219-project
spec:
  selector:
    app: payment-orchestrator
  ports:
  - port: 80
    targetPort: 8000