apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-orchestrator
  namespace: nt219-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-orchestrator
  template:
    metadata:
      labels:
        app: payment-orchestrator
    spec:
      initContainers:
      - name: run-migrations
        image: payment_orchestrator:v1
        command: ["php", "artisan", "migrate", "--force"]
        envFrom:
        - secretRef:
            name: payment-env-secret
        env:
        - name: DB_CONNECTION
          value: pgsql
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"

      containers:
      - name: payment-orchestrator
        image: payment_orchestrator:v1
        ports:
        - containerPort: 80
        # GIÁP KHIÊN CHO PAYMENT ORCHESTRATOR
        volumeMounts:
        - name: cert-volume
          mountPath: /var/www/html/storage/certs
          readOnly: true
        envFrom:
        - secretRef:
            name: payment-env-secret
        env:
        - name: DB_CONNECTION
          value: pgsql
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: laravel
        - name: DB_PASSWORD
          value: root
        - name: REDIS_HOST
          value: redis-service

      # KHAI BÁO KHO CHỨA SECRET
      volumes:
      - name: cert-volume
        secret:
          secretName: client-certs
---
apiVersion: v1
kind: Service
metadata:
  name: payment-orchestrator-service
  namespace: nt219-project
spec:
  selector:
    app: payment-orchestrator
  ports:
  - port: 80
    targetPort: 80