# infra/k8s/softhsm-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: softhsm
  namespace: nt219-project
spec:
  selector:
    matchLabels:
      app: softhsm
  template:
    metadata:
      labels:
        app: softhsm
    spec:
      containers:
      - name: softhsm
        image: softhsm-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: softhsm-cert-volume
          mountPath: /etc/certs
          readOnly: true

      volumes:
      - name: softhsm-cert-volume
        secret:
          # SỬA DÒNG NÀY: Từ softhsm-certs thành master-mtls-certs
          secretName: master-mtls-certs 
---
apiVersion: v1
kind: Service
metadata:
  name: softhsm
  namespace: nt219-project
spec:
  selector:
    app: softhsm
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888