apiVersion: apps/v1
kind: Deployment
metadata:
  name: softhsm
  namespace: nt219-project
spec:
  selector:
    matchLabels:
      app: softhsm
  template:
    metadata:
      labels:
        app: softhsm
    spec:
      containers:
      - name: softhsm
        image: softhsm-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8888
        # GIÁP KHIÊN CHO SOFTHSM
        volumeMounts:
        - name: softhsm-cert-volume
          mountPath: /etc/certs
          readOnly: true

      # KHAI BÁO KHO CHỨA SECRET
      volumes:
      - name: softhsm-cert-volume
        secret:
          secretName: softhsm-certs
---
apiVersion: v1
kind: Service
metadata:
  name: softhsm
  namespace: nt219-project
spec:
  selector:
    app: softhsm
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888